### ISSUE TITLE
Drupal 9 - "The website encountered an unexpected error" when Editing Event Series/Instances

### ISSUE THREAD

**Issue by dwells-tn** [ymcatwincities/openy_gated_content#30] opened 2020-09-11 20:22 UTC
**Issue Description** - You get the Drupal white page of death when you try to edit an existing event series or instance on the Drupal 9 Alpha Sandbox.

**How to Recreate**

- Go to Admin/Content/Event/Event Series or Admin/Content/Event/Event Instances
- Click on the edit button to edit a piece of content
- Break site

[Initially identified issue on Carnation sandbox.](https://sandbox-carnation-std-virtual-y-d9.openy.org/admin/content/events/instances) Present on all three themes.

**Comment by sarah-halby** [comment] 2021-01-18 16:22
@podarok can you review and see if this is still an issue in Drupal 9.0 & 9.1? I'll get a bug created in Jira for tracking.

**Comment by podarok** [comment] 2021-01-19 10:36
Can't reproduce @sarah-halby 
Everything works like expected
Can't catch any "Break site" issues
Could be related to memory issues

**Comment by sarah-halby** [comment] 2021-01-21 17:16
@hamrant or @anpolimus can either of you reproduce this issue above? @dwells-tn - could you retest when you get a chance? I want to confirm that it is no longer an issue before we close this out.

**Comment by hamrant** [comment] 2021-01-21 17:28
Tested on [https://sandbox-carnation-std-virtual-y-d9.openy.org/](https://sandbox-carnation-std-virtual-y-d9.openy.org/) works fine for me.

@dwells-tn next time you can try to enable `Database Logging` module on `/admin/modules` and share error from logs, this can help with the investigation.

**Comment by sarah-halby** [comment] 2021-02-09 15:00
@dwells-tn tested this morning and it looks good. Closing ticket cc @hamrant @podarok @anpolimus

**Closed by sarah-halby** 2021-02-09 15:00 UTC
Labels: Status: Needs more info, Type: Bug
