### ISSUE TITLE
Event Calendar shows two event instances on Daylight Savings Time days

### ISSUE THREAD

**Issue by rdwash** [ymcatwincities/openy_gated_content#126] opened 2021-03-09 21:12 UTC
If a member has their Daylight Saving Time (DST) setting turned on (on their OS) and is viewing the event calendar, specifically 3/14/2021 (first DST of this year), they are seeing classes for both 3/14 and 3/21:

![image](https://user-images.githubusercontent.com/5083127/110536982-b3f65c80-80e7-11eb-9269-14789b489751.png)

If a member has their Daylight Saving Time (DST) setting turned off (on their OS) or is in a time zone that doesn't recognize DST (including UTC) and is viewing the event calendar, specifically 3/14/2021 (first DST of this year), they are seeing classes for only 3/14 (this example is from the Arizona time zone):

![image](https://user-images.githubusercontent.com/5083127/110537149-eacc7280-80e7-11eb-9cb1-a8600667cbd2.png)

This was brought to our attention by one of our YMCAs and I imagine others will see this issue as well. 

This is probably something that won't get fixed this week, so there's a 6 month window now for a solution.

**Comment by sarah-halby** [comment] 2021-03-09 21:48
Per the conversation with @froboy & @rdwash on Slack, we've added this to the Jira backlog: https://openy.atlassian.net/browse/PRODDEV-260 to be fixed before Daylight Savings Time rolls around again in fall 2021. Given the timing and the impact on 3/14 only, development time, testing, and implementation on all sites is unrealistic given the current bandwidth across the teams. Link to the discussion here: https://openy.slack.com/archives/C01715RK630/p1615325518007500

**Comment by hamrant** [comment] 2021-07-09 10:20
@rdwash I tried to reproduce this issue:
- Created Recurring event for March 2022
- Navigated on the schedule page to march (If you do this by arrows navigation it will be stuck on the October, so I used March 2022 timestamp in the URL - `/virtual-ymca#/schedule?startDate=1647756000000`)

So this is how it looks for my timezone:

![Screenshot from 2021-07-08 18-11-26](https://user-images.githubusercontent.com/13733670/125062900-8fbb8400-e0b7-11eb-9654-d301c7842471.png)

If the event at the end of the day we can see correct daylight savings time handling.
For the rest of the time, it displayed without any problems too: 

![Screenshot from 2021-07-09 13-16-37](https://user-images.githubusercontent.com/13733670/125063379-14a69d80-e0b8-11eb-9dfa-3cff474a76d8.png)

So looks like it works correctly and I can't reproduce this issue.

**Comment by sarah-halby** [comment] 2021-07-12 15:27
@froboy copying you on this ticket - please take a look at @hamrant update.

**Comment by sarah-halby** [comment] 2021-07-20 14:59
@rdwash & @froboy - pinging you again in regards to the ticket and the discovery work that @hamrant has done so far.

**Comment by froboy** [comment] 2021-07-20 16:05
@hamrant @sarah-halby thanks for the testing. I'm fine closing this at this point. Apologies for the long delays.

**Closed by froboy** 2021-07-20 16:05 UTC
Labels: Level: Middle, PR: Needs work, Severity: Minor, Type: Bug

**Comment by sarah-halby** [comment] 2021-07-20 16:07
Thanks @froboy I'll move the Jira ticket to the backlog, just in case this resurfaces later this year. Then we'll have the testing notes for reference.
